development:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: dawarich_production
