# config/database.ci.yml
test:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV["POSTGRES_DB"] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
