default: &default
  adapter: postgis
  encoding: unicode
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 10 } %>
  timeout: 5000

development:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'dawarich_development' %>
  queue:
    <<: *default
    database: <%= ENV['DATABASE_QUEUE_NAME'] || 'dawarich_development_queue' %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['DATABASE_CABLE_NAME'] || 'dawarich_development_cable' %>
    migrations_paths: db/cable_migrate

test:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'dawarich_test' %>
  queue:
    <<: *default
    database: <%= ENV['DATABASE_QUEUE_NAME'] || 'dawarich_test_queue' %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['DATABASE_CABLE_NAME'] || 'dawarich_test_cable' %>
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'dawarich_production' %>
  queue:
    <<: *default
    database: <%= ENV['DATABASE_QUEUE_NAME'] || 'dawarich_production_queue' %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['DATABASE_CABLE_NAME'] || 'dawarich_production_cable' %>
    migrations_paths: db/cable_migrate

staging:
  primary:
    <<: *default
    database: <%= ENV['DATABASE_NAME'] || 'dawarich_staging' %>
  queue:
    <<: *default
    database: <%= ENV['DATABASE_QUEUE_NAME'] || 'dawarich_staging_queue' %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV['DATABASE_CABLE_NAME'] || 'dawarich_staging_cable' %>
    migrations_paths: db/cable_migrate
