# config/schedule.yml

bulk_stats_calculating_job:
  cron: "0 */6 * * *" # every 6 hour
  class: "BulkStatsCalculatingJob"
  queue: stats

area_visits_calculation_scheduling_job:
  cron: "0 0 * * *" # every day at 0:00
  class: "AreaVisitsCalculationSchedulingJob"
  queue: visit_suggesting

# Disabled until fixed
# visit_suggesting_job:
#   cron: "0 1 * * *" # every day at 1:00
#   class: "VisitSuggestingJob"
#   queue: visit_suggesting

watcher_job:
  cron: "0 */1 * * *" # every 1 hour
  class: "Import::WatcherJob"
  queue: imports

app_version_checking_job:
  cron: "0 */6 * * *" # every 6 hours
  class: "AppVersionCheckingJob"
  queue: default

telemetry_sending_job:
  cron: "0 */1 * * *" # every 1 hour
  class: "TelemetrySendingJob"
  queue: default
